coordinate:
  lat: 39.17449999999999
  lng: -76.8015413
description: Tenable Network Security transforms security technology for the business
  needs of tomorrow through comprehensive solutions that provide continuous visibility
  and critical context, enabling decisive actions to protect your organization. Tenable
  eliminates blind spots, prioritizes threats, and reduces exposure and loss. With
  more than one million users and more than 20,000 enterprise customers worldwide,
  organizations trust Tenable for proven security innovation.
image: http://baltimoretech.org/wp-content/uploads/2016/06/croppedImg_1902335550.jpeg
location: 7021 Columbia Gateway Dr, Columbia, MD 21046, United States
name: Tenable Network Security
url: http://www.tenable.com/
