---
name: Product Design and Animation
description: "<p>This is a group for anyone interested in learning about design and
  prototyping tools and create user experiences for Mobile, Desktop, Wearables and
  beyond! We will be sharing knowledge, tips, workflow, projects made in Sketch. We
  would also explore other design tools and plugins.</p>"
url: https://www.meetup.com/Product-Design-and-Animation/
