---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _data/organizations
  label: Organizations
  create: documents
  match: "**/*"
  new_doc_ext: json
- type: directory
  path: _data/events
  label: Events
  create: all
  match: "**/*"
  new_doc_ext: json
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _jobs
  label: Jobs
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
