---
user_login: northeastcarsecurity
user_nicename: northeastcarsecurity
user_email: northcarsec@gmail.com
user_url: ''
user_registered: '2018-03-22 09:21:05'
display_name: North East Car Security
first_name: North
last_name: East Car Security
user_status: ''
roles: member
name: North East Car Security
type: ''
profession: ''
education: ''
skills: []
picture: North East Car Security
resume_url: ''
general info:
  name: North East Car Security
  location: Other
  bio: NECS recognition has been constructed via turning in exquisite customer service
    and we\'re proud to be recognized as one in each of Australia’s leading <a href=\"http://www.northeastcarsecurity.com.au/vehicle-safety-systems/\"
    rel=\"nofollow\">car gps Adelaide</a> Experts. It\'s far this popularity and ou
links:
  website: http://www.northeastcarsecurity.com.au/
professional info: {}
